### ISSUE TITLE
SSHPASS error

### ISSUE THREAD

**Issue by jdsteinbach** [evolution/wordpress#115]
`yo evolve wordpress` errored out on its check for sshpass

```
✖ Could not find dependencies:
	- sshpass

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__
 ´   `  |° ´ Y `

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Missing prerequisites
    at exited (/Users/jamessteinbach/.cache/yeoman/evolution/wordpress/v1.3.11/lib/yeoman/index.js:64:17)
    at ChildProcess.emit (events.js:129:20)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

Would be great if this could be installed as a dependency automatically, or include installation instructions in Readme.md.

**Comment by jdsteinbach** [comment]
nvm, just saw the link for this :)
