### ISSUE TITLE
Cambrian import fails

### ISSUE THREAD

**Issue by weeirishman** [evolution/wordpress#120]
**Issue 1:**
Had to `chmod` the `./bin/import` file to get it to run.  Doubt this has any impact on issue 2.

**Issue 2:**
Importer aborts with the following trace:

```
Cambrian export file for your existing site: /Users/daverobb/Downloads/cambrian-290f8e0755--www-onlinecolleges-net.zip
Extracting /Users/daverobb/Downloads/cambrian-290f8e0755--www-onlinecolleges-net.zip to /var/folders/pk/r0c7h8y17m91fy0lspnfrkjc0000gp/T/cambrian-290f8e0755--www-onlinecolleges-net
domain cleanup: replacing www\.onlinecolleges\.net with local.onlinecolleges.net
importing sql via: bundle exec cap local evolve:db:exec[/var/folders/pk/r0c7h8y17m91fy0lspnfrkjc0000gp/T/cambrian-290f8e0755--www-onlinecolleges-net/wordpress.sql]

/Users/daverobb/Sites/OnlineColleges.net-evolution/bower_components/evolution-wordpress/node_modules/deasync/index.js:46
				throw err;
				      ^
Error: Command failed: cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host local.onlinecolleges.net: fingerprint 7e:2d:71:73:aa:c6:72:55:97:1c:a2:5c:1c:6b:f6:49 does not match for "local.onlinecolleges.net,192.168.33.10"
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/verifiers/secure.rb:50:in `process_cache_miss'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/verifiers/secure.rb:35:in `verify'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/verifiers/strict.rb:16:in `verify'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/verifiers/lenient.rb:15:in `verify'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:173:in `verify_server_key'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:68:in `exchange_keys'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/algorithms.rb:364:in `exchange_keys'
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.
```

**Comment by weeirishman** [comment]
Also when I went to do this manually so I can keep moving here I noticed the Cambrian export didn't bundle up anything from the `uploads` dir on production.

**Comment by EvanK** [comment]
Sorry it took me a while to get to this, but it looks like a problem with ssh key conflicts.

Your system sees that this new evolution site doesn't match the existing ssh fingerprint for the genesis site from which you're upgrading (since they both share the same hostname of `local.onlinecolleges.net`). Try removing the known hosts like so:

```
ssh-keygen -R local.onlinecolleges.net
ssh-keygen -R 192.168.33.10
```

And then run the import again

**Comment by EvanK** [comment]
@weeirishman Per #122, I've added a fix for the ssh fingerprint/known hosts issue
